// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Description: typeof import('./components/description/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Form: typeof import('./components/form/index.vue')['default']
    Icon: typeof import('./components/icon/index.vue')['default']
    Page: typeof import('./components/page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/sideBar/index.vue')['default']
    SideBarItem: typeof import('./components/sideBar/sideBarItem.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
    TableItem: typeof import('./components/table/tableItem.vue')['default']
  }
}

export {}
